language: python
python:
    - 3.4
    - 3.5
addons:
  postgresql: "9.4"
services:
  - postgresql
before_script:
  - mv config/config.test.ini config/config.ini
install: pip install -r requirements.dev.txt
script: python manage.py test
