language: python
python:
    - 3.4
    - 3.5
install: pip install -r requirements.dev.txt
script: python manage.py test
services:
  - postgresql
addons:
  postgresql: "9.5"
before_script:
  - psql -c 'create database db;' -U postgres