db:
  restart: always
  image: postgres:9.4
  volumes:
    - postgres_db:/var/lib/postgresql/data
django:
  restart: always
  build: .
  expose:
    - "8000"
  volumes:
    - django_www:/usr/src/app/www
  links:
    - db
  command: ./start.sh
nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes_from:
    - django
  links:
    - django
