version: '2'
services:
  db:
    restart: always
  backend:
    restart: always
    volumes:
      - backend:/backend
    command: /usr/bin/supervisord
  frontend:
    restart: always
    volumes:
      - frontend:/frontend
    command: npm start
  nginx:
    restart: always
    environment:
      - domain=lesspass.com
volumes:
  backend:
  frontend: