version: '2'
services:
  db:
    restart: always
    image: postgres:9.5
    volumes:
      - postgresql:/var/lib/postgresql/data
  backend:
    restart: always
    build: ./backend
    volumes:
      - backend:/backend
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    restart: always
    build: ./frontend
    volumes:
      - frontend:/frontend
    ports:
     - "8080:8080"
  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    environment:
      - domain=lesspass.com
    volumes:
      - ./nginx/ssl:/certificates
    volumes_from:
      - backend
    links:
      - backend
      - frontend
volumes:
  postgresql:
  backend:
  frontend: