version: '2'
services:
  db:
    image: postgres:9.5
    volumes:
      - postgresql:/var/lib/postgresql/data
  backend:
    build: ./backend
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/frontend
      - node_modules:/frontend/node_modules
    ports:
     - "8080:8080"
    command: npm run dev
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    environment:
      - domain=lesspass.com
    volumes:
      - ./nginx/ssl:/certificates
    volumes_from:
      - backend
    links:
      - backend
      - frontend
volumes:
  postgresql:
  node_modules:
