version: '2'
services:
  db:
    image: postgres:9.5
    volumes:
      - postgresql:/var/lib/postgresql/data
  backend:
    build: ./backend
    expose:
      - '8000'
    depends_on:
      - db
  frontend:
    build: ./frontend
  nginx:
    build: ./nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/ssl:/certificates
    volumes_from:
      - backend
    links:
      - backend
      - frontend
volumes:
  postgresql:
